# Generated by Django 4.0.5 on 2023-01-30 17:18

import class_room.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('class_room', '0003_student_image_teacher_image_alter_student_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(upload_to='students/images/', validators=[class_room.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='image',
            field=models.ImageField(upload_to='teachers/images/', validators=[class_room.validators.validate_file_size]),
        ),
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='room', to='class_room.teacher')),
                ('participants', models.ManyToManyField(related_name='class_room', to='class_room.student')),
            ],
        ),
    ]
