# Generated by Django 4.0.5 on 2023-11-02 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('class_room', '0004_alter_student_image_alter_teacher_image_classroom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='department',
        ),
        migrations.RemoveField(
            model_name='student',
            name='section',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='department',
        ),
    ]
